---

- name: assert | Test if jenkins_port is set correctly
  ansible.builtin.assert:
    that:
      - jenkins_port is defined
      - jenkins_port is number
      - jenkins_port > 0
      - jenkins_port < 65535
    quiet: yes

- name: assert | Test if jenkins_listen_address is set correctly
  ansible.builtin.assert:
    that:
      - jenkins_listen_address is defined
      - jenkins_listen_address is string
    quiet: yes

- name: assert | Test if jenkins_version is set correctly
  ansible.builtin.assert:
    that:
      - jenkins_version is string
    quiet: yes
  when:
    - jenkins_version is defined
