---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    - role: buluma.java
      java_default_version: 11
    - role: buluma.locale
    - role: buluma.core_dependencies
