---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    - java_default_version: 17
      role: buluma.java
    - role: buluma.locale
    - role: buluma.core_dependencies
