---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    - role: robertdebock.java
      java_default_version: 11
    - role: buluma.locale
    - role: buluma.core_dependencies
