---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Check web ui
      ansible.builtin.uri:
        url: "http://localhost:8080/login"
        return_content: true
      register: jenkins_check_web_ui
      failed_when:
        - "'Jenkins' not in jenkins_check_web_ui.content"
